### ISSUE TITLE
trying to get sgminer with a sappire 280x live and the amd sdk borks

### ISSUE THREAD

**Issue by tunage** [sgminer-dev/sgminer#103]
I appear to have the driver loaded successfully;

lspci -k
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Tahiti XT [Radeon HD 7970/R9 280X]
        Subsystem: PC Partner Limited / Sapphire Technology Device 3001
        Kernel driver in use: radeon

installing sgminer, I get the following output;

---
## sgminer 4.1.0

Configuration Options Summary:

  Use git version......: no
  libcurl(GBT+getwork).: Enabled: -lcurl
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: NOT FOUND. GPU mining support DISABLED
configure: error: OpenCL not found

I have all the packages from the readme installed but ADL_SDK_6.0.zip , it has no make file and the instructions say to use this;
gcc main.c -o adlutil -DLINUX -ldl -I /home/coined/include/

but that explodes with missing libraries.

root@coined:/home/coined# cd adlutil
root@coined:/home/coined/adlutil# make
make: **\* No targets specified and no makefile found.  Stop.
root@coined:/home/coined/adlutil# ls
adlutil.sln             adlutil.vcproj                main.c
ADLUTIL User Guide.doc  Linux build instructions.txt
root@coined:/home/coined/adlutil# gcc main.c -o adlutil -DLINUX -ldl -I /home/coined/include/
In file included from ../include/adl_sdk.h:19:0,
                 from main.c:15:
../include/adl_structures.h:1670:2: error: unknown type name ‘wchar_t’
  wchar_t strPathName[ADL_MAX_PATH];
  ^
../include/adl_structures.h:1672:2: error: unknown type name ‘wchar_t’
  wchar_t strFileName[ADL_APP_PROFILE_FILENAME_LENGTH];
  ^
../include/adl_structures.h:1674:2: error: unknown type name ‘wchar_t’
  wchar_t strTimeStamp[ADL_APP_PROFILE_TIMESTAMP_LENGTH];
  ^
../include/adl_structures.h:1676:2: error: unknown type name ‘wchar_t’
  wchar_t strVersion[ADL_APP_PROFILE_VERSION_LENGTH];
  ^
main.c: In function ‘GetValue’:
main.c:814:2: warning: format ‘%d’ expects argument of type ‘int *’, but argument 4 has type ‘int’ [-Wformat=]
  fscanf_s( file,"%32s %d\n", sField, 33, iValue);
  ^
main.c:814:2: warning: too many arguments for format [-Wformat-extra-args]
main.c: In function ‘GetHex’:
main.c:827:2: warning: format ‘%X’ expects argument of type ‘unsigned int *’, but argument 4 has type ‘int’ [-Wformat=]
  fscanf_s( file,"%32s %X\n", sField, 33, iValue);
  ^
main.c:827:2: warning: too many arguments for format [-Wformat-extra-args]
main.c: In function ‘GetFloat’:
main.c:840:2: warning: format ‘%f’ expects argument of type ‘float *’, but argument 4 has type ‘int’ [-Wformat=]
  fscanf_s( file,"%32s %f\n", sField, 33, fValue);
  ^
main.c:840:2: warning: too many arguments for format [-Wformat-extra-args]

Here are the libraries...

root@coined:/home/coined/adlutil# grep -lir ADL_MAX_PATH ../
../include/adl_structures.h
../include/adl_defines.h
^C

Any thoughts on what I am missing?

**Comment by papaiatis** [comment]
This helped me with the "OpenCL not found" error:
` sudo apt-get install ocl-icd-opencl-dev `

**Comment by Technophant** [comment]
Exactly. ocl-icd-opencl-dev should be included as a prerequisite. Worked for me after installed.
