### ISSUE TITLE
Scrypt-Jane

### ISSUE THREAD

**Issue by Bllacky** [sgminer-dev/sgminer#283]
Hello!

Is it possible to merge the Scrypt-Jane branch into sgminer 5.0 ?

I know the Scrypt-Jane branch is working because I am using it.
Just needs to be adapted I suppose.

**Comment by platinum4** [comment]
@ystarnaud can you make this happen? ;D

**Comment by lpedretti** [comment]
I'm also interested in merging scrypt-jane support, with 8 gb cards even high nfactor coins are minable pretty well.
I'll give a shot at the sources here and see if they give me any good results, maybe i'll even try to merge the kernel to the main branch. but i'm not familiarized with opencl and the specifics of the architecture to debug any problems, so it'll be a blind try.

**Comment by Bllacky** [comment]
This algo is dead I think.
