### ISSUE TITLE
AMD GPUs not Found with Intel Onboard GPU Present - New issue to Sgminer 5, same rigs run earlier versions perfectly

### ISSUE THREAD

**Issue by Atomicchaos** [sgminer-dev/sgminer#338]
I posted this issue on Bitcointalk, but have since figured out a workaround, but I wanted to figure out if it is a bug, or something I am doing wrong. Sgminer 5 will not find any AMD GPUs on my systems that run 4.1 perfectly unless I completely uninstall the onboard intel GPU. 

Here's what I get when the Intel GPU is present and launch SGMiner 5:
C:\sgminer-5.0-pre-release-2014-07-08-win32>sgminer -n
[11:04:31] CL Platform vendor: Intel(R) Corporation
[11:04:31] CL Platform name: Intel(R) OpenCL
[11:04:31] CL Platform version: OpenCL 1.1
[11:04:31] Error -1: Getting Device IDs (num)
[b][11:04:31] clDevicesNum returned error, no GPUs usable
[11:04:31] 0 GPU devices max detected[/b]

Once I remove the Intel on-board GPU from the control panel, and relaunch, it works perfectly. Since this does not manifest itself in earlier versions of SGminer, is this a bug, or something I am doing wrong? As a side note, I've also tried using the -d parameter to ignore the Intel card, but this doesn't work either.

**Comment by alexbadescu24** [comment]
Hi,

I have the same problem. I want to mine some dgb with my laptop just for fun and it uses my internal GPU. I have an AMD r7 m265 and I did not understand how can I change the GPU. I manage to see them like you have done above, but should I change something in the sgminer.conf file. I know it's stupid but I am at the beginning and I do not know so much.

**Comment by togheter** [comment]
Hello there.I quit mining on eobot and i started mining on
http://micromining.cloud?r=3Hn9KmYbfoJzEWQH3zDjYobnNAvmPy7fzg   , this is
my referal link.
It`s very simple to install on your laptop and start mining.i have already
1000 satoshi in 8 hour.
