### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by 2011** [sgminer-dev/sgminer#390]
Sorry if I am missing something obvious. Downloaded a "release," and attempted the obvious:

$ autoreconf -i
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file`./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file`m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file`m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file`m4/lt~obsolete.m4'
configure.ac:52: installing './compile'
configure.ac:17: installing './config.guess'
configure.ac:17: installing './config.sub'
configure.ac:22: installing './install-sh'
configure.ac:22: installing './missing'
Makefile.am: installing './depcomp'

$ ./configure

[...]

configure: creating ./config.status
config.status: creating Makefile
config.status: creating submodules/Makefile
config.status: creating ccan/Makefile
config.status: creating lib/Makefile
config.status: creating sph/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in submodules/jansson (/tmp/sgminer-5.0.0/submodules/jansson)
configure: WARNING: no configuration information is in submodules/jansson

---
## sgminer 5.0.0

Configuration Options Summary:

  Use git version......: no
  libcurl(GBT+getwork).: Enabled: -lcurl 
  curses.TUI...........: FOUND: -lncurses
  OpenCL...............: FOUND. GPU mining support enabled
  ADL..................: SDK NOT found, GPU monitoring support DISABLED

Compilation............: make (or gmake)
  CPPFLAGS.............: 
  CFLAGS...............: -g -O2
  LDFLAGS..............:  -lpthread
  LDADD................:  -lcurl  submodules/jansson/src/.libs/libjansson.a -lpthread -lOpenCL    -lm -lrt

Installation...........: make install (as root if needed, with 'su' or 'sudo')
  prefix...............: /usr/local

$ make
make  all-recursive
make[1]: Entering directory '/tmp/sgminer-5.0.0'
Making all in lib
make[2]: Entering directory '/tmp/sgminer-5.0.0/lib'
  GEN      arg-nonnull.h
  GEN      c++defs.h
  GEN      warn-on-use.h
  GEN      signal.h
  GEN      string.h
make  all-recursive
make[3]: Entering directory '/tmp/sgminer-5.0.0/lib'
make[4]: Entering directory '/tmp/sgminer-5.0.0/lib'
  CC       dummy.o
  AR       libgnu.a
make[4]: Leaving directory '/tmp/sgminer-5.0.0/lib'
make[3]: Leaving directory '/tmp/sgminer-5.0.0/lib'
make[2]: Leaving directory '/tmp/sgminer-5.0.0/lib'
Making all in submodules
make[2]: Entering directory '/tmp/sgminer-5.0.0/submodules'
Making all in jansson
make[3]: Entering directory '/tmp/sgminer-5.0.0/submodules/jansson'
make[3]: **\* No rule to make target 'all'.  Stop.
make[3]: Leaving directory '/tmp/sgminer-5.0.0/submodules/jansson'
Makefile:501: recipe for target 'all-recursive' failed
make[2]: **\* [all-recursive] Error 1
make[2]: Leaving directory '/tmp/sgminer-5.0.0/submodules'
Makefile:1301: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/tmp/sgminer-5.0.0'
Makefile:610: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by csallen1204** [comment]
I had this issue as well when trying to build on a CentOS 7 server. If I just download the master.zip file, I'm not able to use the "git submodule" commands that fix this issue. You may want to suggest that they do a "git clone" to pull the code first in the *nix instructions.
