### ISSUE TITLE
Error 61- after cmpiling on Linux Mint (Semi-Noob)

### ISSUE THREAD

**Issue by VictorHatley** [sgminer-dev/sgminer#424]
I recently started mining cryptocoins using my desktop in a Windows 7 environment, and am extremely happy with my results, getting around 165-170 kH/s using sph-sgminer. So, I decided to try CPU mining (simultaneous)  using Poolers CPU Miner. But couldn't get the CPU Miner to start. It would open then immediately close. Did a lot of troubleshooting with zero results.

So, I decided to try using the BAMT and SMOS Linus live USB's but I need more in the OS than just the miners, and when I tried to add the CPU miner the GPU miner would crash. BUT, before I added anything I had sph-sgminer getting 185-190 kH/s.

So, I migrated to Linux Mint to get the OS I needed. I first followed these instructions: http://ubuntuforums.org/showthread.php?t=2243386 in setting up darkcoin-cpuminer-1.2c, and it worked. I'm mining on 7 cores and getting from 20-25 kH/s per core...

So, I followed these instructions to set up sgminer: http://ubuntuforums.org/showthread.php?t=2243387. And after much troubleshooting finally got the darkgpu miner to start, but once the terminal opens I get (I removed the time-stamps):

---

Initialising kernel darkcoin-mod.cl with nfactor 10, n 1024
Maximum buffer memory device 0 supports says 268435456
Your settings come to 536870912
Error -61: clCreateBuffer (padbuffer8), decrease TC or increase LG
Failed to init GPU thread 0, disabling device 0

---

I have tried everything to get sgminer working in the Mint install, and when I looked for the .config file, (in /sgminer) I can't find it. I added the "export GPU MAX ALLOC PERCENT=100" to the /etc/profile file. Tried starting using the darkgpu.sh, then started using ./sgminer -k x11 -I 13, etc. and still get the same thing. (Although after starting using the ./sgminer command I now have a .bin file in my home folder.)

Here are the contents of my darkcpu.sh file (this works great):

---
# !/bin/bash

cd ~/darkcoin-cpuminer-1.2c
./minerd -a X11 -o stratum+tcp://us-west.multipool.us:11111 -u XXXXXX.1 -p X --threads=7

---

Here are the contents of the darkGPU.sh file (tis is the one throwing the error):

---
# !/bin/bash

cd ~/sgminer
export DISPLAY=:0
export GPU_MAX_ALLOC_PERCENT=100
export GPU_USE_SYNC_OBJECTS=1
./sgminer -k x11mod -o stratum+tcp://us-west.multipool.us:11111 -u XXXXXX.1 -p X -I 13 --thread-concurrency 4096

---

I would post the .config files, but I can't find them in any of the Linux Mint files...

I really appreciate any kind of help here, I think the combined mining can give me in the area of 300-350 kH/s. Here's the details of my system:

HP Pavillion P7-1254
A6-3620 APU w/Radeon HD 6530D Graphics
Dual Boot:
Windows 7 Home Pro SP1 (sph-sgminer works, Poolers CPUMiner 2.3, and 2.4, both 32 and 64 bit...none works. Starts then immediately closes.
Linux Mint 17.2 Cinnamon 64 bit (here darkcoin-CPUminer-1.2c works, sgminer doesn't)

Any advice you can give would be sincerely appreciated. I'm only a hobbyist in mining, and an intermediate NOOB in Linux. But with that said, I'd like to mine using the Linux Mint system. 
THANKS A LOT for just reading about my issues, and even more for helping me fix them.
Vic

**Comment by mrbrdo** [comment]
Judging by the error there is not enough VRAM on your GPU for the settings you are using. Your settings would need twice as much VRAM as you have on your GPU.
As it says you should decrease thread-concurrency or increase the lookup-gap. Based on output you could try thread concurrency 2048. Try to google for optimal sgminer settings for your GPU.
