### ISSUE TITLE
ubuntu 16.04.3 build

### ISSUE THREAD

**Issue by bobozm** [sgminer-dev/sgminer#486]
heads up for everybody 
you will have to manually install jansson into the submodules/jansson file
jansson git clone has bug you will have to tar the file from jansson 
and of course 
autoconf -i
./configure
make 
make install
!!!!Happy building!!!

**Comment by ukos-git** [comment]
this is not true. You have to run
```
git submodule init
git submodule update
```
and then `autogen.sh` to get jansson

**Comment by bobozm** [comment]
some people are having issues with git command
it has bug that places two of the same file which in return causes a build err

**Comment by ukos-git** [comment]
could you report which files are causing conflicts?

**Comment by bobozm** [comment]
just to clarify are you autogen.sh sgminer or jansson

**Comment by bobozm** [comment]
yeap it worked

**Comment by bobozm** [comment]
I was git clone from source and this was the one with bug 
it gives two jansson_private_config.h files

**Comment by ukos-git** [comment]
The header file `./submodules/jansson/ansson_private_config.h` is located in the submodule. Sometimes if you had previously filled this folder with something else before initializing/updating the submodule, git can get confused. It would be good if the submodules could get initialized in a more intuitive way, i.e. when cloning directly but that would be a git problem.

If the problem resolved on your side and you can not add a MR to it, please close it.
