### ISSUE TITLE
sgminer opencl problem.

### ISSUE THREAD

**Issue by kominikjs** [sgminer-dev/sgminer#510]
Hi all.
I'm using sgminer for vertcoin mining.
After build, whenever I execute sgminer there is crash on clBuildProgram.
Below is cause of crash.

[05:04:54] Started sgminer 5.1.1-19-g8bf1-dirty
[05:04:54] * using Jansson 2.7
[05:04:54] WARNING: GPU_MAX_ALLOC_PERCENT is not specified!
[05:04:54] WARNING: GPU_USE_SYNC_OBJECTS is not specified!
[05:04:54] Probing for an alive pool
[05:04:56] Switching p2p-spb.xyz to stratum+tcp://p2p-spb.xyz:9171
[05:04:58] p2p-spb.xyz difficulty changed to 32
[05:04:58] Startup GPU initialization... Using settings from pool p2p-spb.xyz.
[05:04:58] Startup Pool No = 0
[05:04:58] Building binary ckolivasMali-G71gw256l8lg2tc7552nf10.bin

// Below is root cause of crash!!!
[05:04:58] Error -43: Building Program 2 (clBuildProgram) = -I "." -I "./kernel" -I "." -D WORKSIZE=256 -I "/usr/local/bin" -D LOOKUP_GAP=2 -D CONCURRENT_THREADS=7552 -D NFACTOR=10
[05:04:58] error: Failed to open directory '"."'
error: Failed to handle include build options
error: encountered invalid build options

As I know, error code -43 means 'CL_INVALID_BUILD_OPTIONS'.

Then I printed the option which clBuildProgram used.
Below is clBuildProgram's option.
-I "." -I "./kernel" -I "." -D WORKSIZE=256 -I "/usr/local/bin" -D LOOKUP_GAP=2 -D CONCURRENT_THREADS=7552 -D NFACTOR=10

Below is env.
OS : Linux(Ubunto 16.04)
GPU : Mali-G71
CPU : MediaTek Helio P23

Is there any way to fix the crash?

**Comment by Saikatsaha1996** [comment]
> Hi all.
> I'm using sgminer for vertcoin mining.
> After build, whenever I execute sgminer there is crash on clBuildProgram.
> Below is cause of crash.
> 
> [05:04:54] Started sgminer 5.1.1-19-g8bf1-dirty
> [05:04:54] * using Jansson 2.7
> [05:04:54] WARNING: GPU_MAX_ALLOC_PERCENT is not specified!
> [05:04:54] WARNING: GPU_USE_SYNC_OBJECTS is not specified!
> [05:04:54] Probing for an alive pool
> [05:04:56] Switching p2p-spb.xyz to stratum+tcp://p2p-spb.xyz:9171
> [05:04:58] p2p-spb.xyz difficulty changed to 32
> [05:04:58] Startup GPU initialization... Using settings from pool p2p-spb.xyz.
> [05:04:58] Startup Pool No = 0
> [05:04:58] Building binary ckolivasMali-G71gw256l8lg2tc7552nf10.bin
> 
> // Below is root cause of crash!!!
> [05:04:58] Error -43: Building Program 2 (clBuildProgram) = -I "." -I "./kernel" -I "." -D WORKSIZE=256 -I "/usr/local/bin" -D LOOKUP_GAP=2 -D CONCURRENT_THREADS=7552 -D NFACTOR=10
> [05:04:58] error: Failed to open directory '"."'
> error: Failed to handle include build options
> error: encountered invalid build options
> 
> As I know, error code -43 means 'CL_INVALID_BUILD_OPTIONS'.
> 
> Then I printed the option which clBuildProgram used.
> Below is clBuildProgram's option.
> -I "." -I "./kernel" -I "." -D WORKSIZE=256 -I "/usr/local/bin" -D LOOKUP_GAP=2 -D CONCURRENT_THREADS=7552 -D NFACTOR=10
> 
> Below is env.
> OS : Linux(Ubunto 16.04)
> GPU : Mali-G71
> CPU : MediaTek Helio P23
> 
> Is there any way to fix the crash?

Hello dear!..
Can you reply me please?

It's Android termux environment ?

If yes please help...

Help wanted..
