### ISSUE TITLE
lpthread problem in android

### ISSUE THREAD

**Issue by Saikatsaha1996** [sgminer-dev/sgminer#516]
Hello help wanted...
Android OS
Termux environment
OpenCL found
But make error
If anybody can please help...

sgminer.c:7762:25: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'

make[2]: Leaving directory '/data/data/com.termux/files/home/sgminer/sph'
make[2]: Entering directory '/data/data/com.termux/files/home/sgminer'
fatal: No names found, cannot describe anything.
  CC       sgminer-sgminer.o
clang-12: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
sgminer.c:282:23: warning: implicit conversion from 'unsigned long long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-const-int-float-conversion]
double current_diff = 0xFFFFFFFFFFFFFFFFULL;
       ~~~~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~
sgminer.c:3589:26: warning: passing 'const char *const *' to parameter of type 'char *const *' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
  execv(initial_args[0], (EXECV_2ND_ARG_TYPE)initial_args);
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/unistd.h:96:44: note: passing argument to parameter '__argv' here
int execv(const char* __path, char* const* __argv);
                                           ^
sgminer.c:5003:3: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
  ^
sgminer.c:5003:25: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
                        ^
sgminer.c:5040:3: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
  ^
sgminer.c:5040:25: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
                        ^
sgminer.c:6660:3: warning: implicit declaration of function 'pthread_setcancelstate' is invalid in C99 [-Wimplicit-function-declaration]
  pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
  ^
sgminer.c:6660:26: error: use of undeclared identifier 'PTHREAD_CANCEL_DISABLE'
  pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
                         ^
sgminer.c:6701:30: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
      pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                             ^
sgminer.c:6956:30: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
      pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                             ^
sgminer.c:6972:26: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
  pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                         ^
sgminer.c:7276:7: warning: implicit declaration of function 'pthread_setcancelstate' is invalid in C99 [-Wimplicit-function-declaration]
      pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
      ^
sgminer.c:7276:30: error: use of undeclared identifier 'PTHREAD_CANCEL_DISABLE'
      pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, NULL);
                             ^
sgminer.c:7282:30: error: use of undeclared identifier 'PTHREAD_CANCEL_ENABLE'
      pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
                             ^
sgminer.c:7283:7: warning: implicit declaration of function 'pthread_testcancel' is invalid in C99 [-Wimplicit-function-declaration]
      pthread_testcancel();
      ^
sgminer.c:7660:3: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
  ^
sgminer.c:7660:25: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
                        ^
sgminer.c:7762:3: warning: implicit declaration of function 'pthread_setcanceltype' is invalid in C99 [-Wimplicit-function-declaration]
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
  ^
sgminer.c:7762:25: error: use of undeclared identifier 'PTHREAD_CANCEL_ASYNCHRONOUS'
  pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, NULL);
                        ^
9 warnings and 10 errors generated.
make[2]: *** [Makefile:977: sgminer-sgminer.o] Error 1
make[2]: Leaving directory '/data/data/com.termux/files/home/sgminer'
make[1]: *** [Makefile:1580: all-recursive] Error 1
make[1]: Leaving directory '/data/data/com.termux/files/home/sgminer'
make: *** [Makefile:682: all] Error 2

**Comment by Pyogenics** [comment]
Android doesn't support all posix threading stuff. However there is a work around. 

Include [this file](https://github.com/tux-mind/libbthread/blob/master/bthread.h) in files where you get pthread related errors. I trust you can do that independently.

**Comment by Saikatsaha1996** [comment]
> Android doesn't support all posix threading stuff. However there is a work around.
> 
> Include [this file](https://github.com/tux-mind/libbthread/blob/master/bthread.h) in files where you get pthread related errors. I trust you can do that independently.

Thank you I will try 😊

**Comment by Saikatsaha1996** [comment]
> Android doesn't support all posix threading stuff. However there is a work around.
> 
> Include [this file](https://github.com/tux-mind/libbthread/blob/master/bthread.h) in files where you get pthread related errors. I trust you can do that independently.

Can you guide me where I need to add this file?
I already installed libbthread

**Comment by Pyogenics** [comment]
Include it wherever you receive pthread errors. From the error in you original message, you should include the file in `sgminer.c`. You may still get errors in other places.

**Comment by Saikatsaha1996** [comment]
> Include it wherever you receive pthread errors. From the error in you original message, you should include the file in `sgminer.c`. You may still get errors in other places.

Please @Pyogenics  help me sir.. after add #include <bthread.h> now i got a single error.. please help..

![Screenshot_2022-05-07-00-37-00-840_com termux](https://user-images.githubusercontent.com/72664192/167202329-2605230b-e929-42f7-b966-fdc9f252d58f.jpg)

**Comment by Pyogenics** [comment]
Try `#include <pthread>` in bthread.h

**Comment by Saikatsaha1996** [comment]
> Try `#include <pthread>` in bthread.h

Okay okay trying

**Comment by Saikatsaha1996** [comment]
> Try `#include <pthread>` in bthread.h

@Pyogenics  WWWWoowwww nice pthread-cancel problem solved 🤗😋🥰

New error found.. but I think it is not pthread-cancel related ..


Thank you so much.. thank you soooo much for your help 😊..!.. finding solutions long time ago.. actually i don't know any programing language that's why facing problem..

I am not miner.. but trying to experiential purpose only..
![Screenshot_2022-05-07-01-18-44-121_com termux](https://user-images.githubusercontent.com/72664192/167207772-879b9786-39b3-4024-b18c-864213e48efd.jpg)

**Comment by Pyogenics** [comment]
I will have to look at the code, further reply will come later.

**Comment by Saikatsaha1996** [comment]
> I will have to look at the code, further reply will come later.

🥰🥰😋😋🤗🤗😄😄 Okay 😃👌👌👌 thank you sooo much!

**Comment by Saikatsaha1996** [comment]
@Pyogenics  this is full error codes


![Screenshot_2022-05-07-01-42-11-559_com termux](https://user-images.githubusercontent.com/72664192/167210296-1669e313-2b50-49f9-9c7e-3964ab564ab0.jpg)

**Comment by Saikatsaha1996** [comment]
@Pyogenics  any solution found please ?  🤗

**Comment by Pyogenics** [comment]
Sorry, had a look but it took me longer than I wanted. Will take me some time :'(

**Comment by Saikatsaha1996** [comment]
> Sorry, had a look but it took me longer than I wanted. Will take me some time :'(

@Pyogenics it ok.. no problem .. I am waiting.. thank you for your response, help, suggestions.. !..

**Comment by Saikatsaha1996** [comment]
> Sorry, had a look but it took me longer than I wanted. Will take me some time :'(

@Pyogenics any solution found sir ? 🤠☺️

**Comment by Saikatsaha1996** [comment]
> > Sorry, had a look but it took me longer than I wanted. Will take me some time :'(
> 
> @Pyogenics any solution found sir ? 🤠☺️

@Pyogenics hello sir!.. after completing with gcc last error solved.. but getting undefined reference to `pthread_cancel'


![Screenshot_2022-05-24-03-18-42-315_com termux](https://user-images.githubusercontent.com/72664192/169911341-4e771f2d-309d-4e08-8137-9d96a5c028f7.jpg)

**Comment by Saikatsaha1996** [comment]
@Pyogenics ultimately cgminer building done ..
Sgminer can't build because of getting undefined reference to pthread-cancel

But sir without your help i can't.. thank you for your help cgminer working fine..
clang did not compile.. i build with gcc..


and also edited some code.. #include bthread.h && #include athread.h

#include <pthread.h>
#include <signal.h>

#define SIG_CANCEL_SIGNAL SIGUSR1
#define PTHREAD_CANCEL_ENABLE 1
#define PTHREAD_CANCEL_DISABLE 0


static int pthread_setcancelstate(int state, int *oldstate) {
    sigset_t   new, old;
    int ret;
    sigemptyset (&new);
    sigaddset (&new, SIG_CANCEL_SIGNAL);

    ret = pthread_sigmask(state == PTHREAD_CANCEL_ENABLE ? SIG_BLOCK : SIG_UNBLOCK, &new , &old);
    if(oldstate != NULL)
    {
        *oldstate =sigismember(&old,SIG_CANCEL_SIGNAL) == 0 ? PTHREAD_CANCEL_DISABLE : PTHREAD_CANCEL_ENABLE;
    }
    return ret;
}


static inline int pthread_cancel(pthread_t thread) {

    pthread_kill(thread, SIG_CANCEL_SIGNAL);
}

After that build completed.. 🤠🤠❤️❤️❤️ thank you so much @Pyogenics 
![Screenshot_2022-05-24-05-54-45-554_com termux](https://user-images.githubusercontent.com/72664192/169925430-fa660b8c-558a-4136-af2b-ce5fed04d3f8.jpg)

**Comment by Saikatsaha1996** [comment]
@Pyogenics Sir
My mistake i am a big idiot...🥲
All problem solved with just need to install libbthread and add
-lbthread flag 

Now all build done sgminer also ..

Thank you ..
Build done without a single error 😊 
Thank you sooooo much for your big help.. ❤️❤️❤️
And thank you too libbthread @tux-mind ..

![Screenshot_2022-05-25-16-09-55-618_com termux](https://user-images.githubusercontent.com/72664192/170245047-56df6f7f-8518-406c-9f99-1ba240db4919.jpg)
